{{- if .Values.jupyterlab.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insurguard.fullname" . }}-jupyterlab
  labels:
    {{- include "insurguard.labels" . | nindent 4 }}
    app.kubernetes.io/name: jupyterlab
spec:
  replicas: {{ .Values.jupyterlab.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyterlab
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jupyterlab
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        {{- include "insurguard.securityContext" . | nindent 8 }}
      containers:
        - name: jupyterlab
          image: {{ .Values.jupyterlab.image }}
          securityContext:
            {{- include "insurguard.containerSecurityContext" . | nindent 12 }}
          command:
            - start-notebook.sh
            - "--NotebookApp.token=''"
            - "--NotebookApp.password=''"
            - "--NotebookApp.allow_origin='*'"
            - "--NotebookApp.ip=0.0.0.0"
            - "--NotebookApp.port=8888"
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
          ports:
            - containerPort: {{ .Values.jupyterlab.port }}
              name: http
          volumeMounts:
            - name: data
              mountPath: /home/jovyan/work
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "insurguard.fullname" . }}-jupyterlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "insurguard.fullname" . }}-jupyterlab
  labels:
    {{- include "insurguard.labels" . | nindent 4 }}
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: {{ .Values.jupyterlab.pvcSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insurguard.fullname" . }}-jupyterlab
  labels:
    {{- include "insurguard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.jupyterlab.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: jupyterlab
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
